### ISSUE TITLE
wsl2 proxy 问题

### ISSUE THREAD

**Issue by ShirleyMatrix** [maicWorkGithub/maicWorkGithub.github.io#1]
_很抱歉在这里提问，找不到联系你的方式如果介意的话随后会删除_

看到了你在wsl项目里提到的issue，就是关于wsl2下使用proxy，我也遇到了同样的问题，请问你最后是如何解决的呢？

是在wsl里重新设置了代理？
还是解决了wsl-›Windows？

😺😺😺

**Comment by maicWorkGithub** [comment]
我去，这样都行 😹 
那个issue说的很清楚了啊，就是wsl使用Windows的暂时不行，他们最近也没有计划让它行。

所以就是：在wsl下开proxy，Windows也可以访问。

~~当然你也可以开两个:smirk:~~

**Comment by ShirleyMatrix** [comment]
谢谢谢谢，已经在wsl下开了proxy
ps. 文章写的真好👍
